[tools]
actionlint = "1.7.12"
dbmate = "2.35.0"
go = "1.26.5"
golangci-lint = "v2.12.2"
node = "24"
pinact = "4.1.0"
sqlc = "1.31.1"
sqlite = "3.53.4"

[env]
CGO_ENABLED = 1
DATABASE_URL = { required = true, redact = true }
PORT = { default = 8000 }
DBMATE_DRIVER = "sqlite3"
DBMATE_MIGRATIONS_DIR = "migrations"
DBMATE_SCHEMA_FILE = "schema.sql"
DBMATE_STRICT = "1"

[tasks."lint:go"]
run = ["go mod tidy -diff", "golangci-lint run"]

[tasks."lint:sqlc"]
run = ["sqlc diff", "sqlc vet"]

[tasks."lint:action"]
run = ["actionlint", "pinact run --check"]

[tasks.test]
run = "go test -v -cover ./..."
