
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE "schema_migrations" (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL
);
CREATE TABLE sqlite_sequence(name,seq);