// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package repository

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO
    "items" ("title")
VALUES
    ($1)
RETURNING
    id, title, updated_at
`

func (q *Queries) CreateItem(ctx context.Context, title string) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, title)
	var i Item
	err := row.Scan(&i.ID, &i.Title, &i.UpdatedAt)
	return i, err
}

const getItems = `-- name: GetItems :many
SELECT
    "id",
    "title",
    "updated_at"
FROM
    "items"
ORDER BY
    "id" ASC
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Title, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE "items"
SET
    "title" = $2,
    "updated_at" = NOW()
WHERE
    "id" = $1
RETURNING
    id, title, updated_at
`

type UpdateItemParams struct {
	ID    int64  `db:"id"`
	Title string `db:"title"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem, arg.ID, arg.Title)
	var i Item
	err := row.Scan(&i.ID, &i.Title, &i.UpdatedAt)
	return i, err
}
